server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     #开启动态路由，从注册中心获取服务名进行路由
      routes:
        #路由的ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment-8001-8002
          #提供服务的路由地址
#         uri: http://localhost:8001
          #匹配后，提供服务的路由地址
          uri: lb://provider-payment
          #断言，以下规则都匹配，才会路由
          predicates:
            - Path=/search/**
            - After=2020-04-28T10:12:12.048+08:00[Asia/Shanghai]

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
